### ISSUE TITLE
`install_vm.py` script: `TypeError: 'type' object is not subscriptable`

### ISSUE THREAD

**Issue by mildas** [ComplianceAsCode/content#10650]
#### Description of problem:
```
Traceback (most recent call last):
  File "/tmp/tmp.J9b2g6mZW8/rpmbuild/BUILD/scap-security-guide-0.1.68/tests/install_vm.py", line 283, in <module>
    def get_virt_install_command(data) -> list[str]:
TypeError: 'type' object is not subscriptable
```

#### SCAP Security Guide Version:
27ed9ad

#### Operating System Version:
RHEL7, RHEL8

#### Steps to Reproduce:

1. `python3 tests/install_vm.py --libvirt=qemu:///system --domain=test_suite_vm --distro=rhel8         --url=${REPO_URL} --extra-repo=${EXTRA_REPO_URL} --ssh-pubkey=/root/.ssh/ssg_id_ecdsa.pub --disk=path=/var/lib/libvirt/images/test_image/test,size=20 --kickstart=tests/kickstarts/test_suite.cfg --ram=2048 --cpu=2`

#### Actual Results:
```
Traceback (most recent call last):
  File "/tmp/tmp.J9b2g6mZW8/rpmbuild/BUILD/scap-security-guide-0.1.68/tests/install_vm.py", line 283, in <module>
    def get_virt_install_command(data) -> list[str]:
TypeError: 'type' object is not subscriptable
```

#### Expected Results:
VM is installed

**Comment by ggbecker** [comment]
Caused by: https://github.com/ComplianceAsCode/content/pull/10607
