### ISSUE TITLE
Automatus Template Mode Doesn't Support Derivatives 

### ISSUE THREAD

**Issue by Mab879** [ComplianceAsCode/content#10677]
#### Description of problem:
When passing a derivative datastream to Automatus and using template mode Automatus crashes.

#### SCAP Security Guide Version:
343bb8936de347432c4fb6c69defc6fcaa6f72fc

#### Operating System Version:
Fedora 38

#### Steps to Reproduce:

1. `./build_product rhel9 --derivatives`
2. `./tests/automatus.py template --datastream build/ssg-cs9-ds.xml --remove-platforms --remove-machine-only  --container ssg_test_suite file_existence` 

#### Actual Results:
Error

#### Expected Results:
Template is tested

#### Additional Information/Debugging Steps:
```
./tests/automatus.py template --datastream build/ssg-cs9-ds.xml --remove-platforms --remove-machine-only  --container ssg_test_suite file_existence
Setting console output to log level INFO
INFO - The base image option has been specified, choosing Podman-based test environment.
INFO - Logging into /home/mburket/code/ComplianceAsCode/content/logs/template-custom-2023-06-02-1159/test_suite.log
WARNING - Nothing has been tested!
Traceback (most recent call last):
  File "/home/mburket/code/ComplianceAsCode/content/./tests/automatus.py", line 511, in <module>
    main()
  File "/home/mburket/code/ComplianceAsCode/content/./tests/automatus.py", line 507, in main
    options.func(options)
  File "/home/mburket/code/ComplianceAsCode/content/tests/ssg_test_suite/template.py", line 47, in perform_template_check
    checker.test_target()
  File "/home/mburket/code/ComplianceAsCode/content/tests/ssg_test_suite/oscap.py", line 683, in test_target
    self._test_target()
  File "/home/mburket/code/ComplianceAsCode/content/tests/ssg_test_suite/rule.py", line 445, in _test_target
    rules_to_test = self._get_rules_to_test()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mburket/code/ComplianceAsCode/content/tests/ssg_test_suite/rule.py", line 298, in _get_rules_to_test
    product_yaml = common.get_product_context(product)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mburket/code/ComplianceAsCode/content/tests/ssg_test_suite/common.py", line 277, in get_product_context
    product_yaml.update(load_product_yaml(yaml_path))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mburket/code/ComplianceAsCode/content/./tests/../ssg/products.py", line 215, in load_product_yaml
    product_yaml = Product(product_yaml_path)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mburket/code/ComplianceAsCode/content/./tests/../ssg/products.py", line 116, in __init__
    self._load_from_filename(filename)
  File "/home/mburket/code/ComplianceAsCode/content/./tests/../ssg/products.py", line 147, in _load_from_filename
    self._primary_data = open_raw(filename)
                         ^^^^^^^^^^^^^^^^^^
  File "/home/mburket/code/ComplianceAsCode/content/./tests/../ssg/yaml.py", line 139, in open_raw
    with codecs.open(yaml_file, "r", "utf8") as stream:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 906, in open
FileNotFoundError: [Errno 2] No such file or directory: '/home/mburket/code/ComplianceAsCode/content/products/cs9/product.yml'
```

**Comment by ggbecker** [comment]
What about providing the `--product rhel9` in the automatus command since we know cs9 is a derivative of rhel9?
