### ISSUE TITLE
Error in scapval validation tool for SCAP 1.3 content

### ISSUE THREAD

**Issue by marcusburghardt** [ComplianceAsCode/content#10975]
#### Description of problem:

`run_scapval.py` tool is reporting error with the following command:
`python3 run_scapval.py --scap-version 1.3 --scapval-path scapval-1.3.6.jar --build-dir scapval-datastream-results`

#### SCAP Security Guide Version:

master as of 2023-08-07

#### Operating System Version:

RHEL8

#### Steps to Reproduce:

1.
2.

#### Actual Results:

```
Command 'java -Xmx1024m -Djava.protocol.handler.pkgs=sun.net.www.protocol -jar scapval-1.3.6.jar -scapversion 1.3 -file scapval-datastream-results/ssg-firefox-ds.xml -valresultfile scapval-datastream-results/ssg-firefox-ds.xml.result.xml -valreportfile scapval-datastream-results/ssg-firefox-ds.xml.report.html' returned 1:
ERROR StatusLogger Error creating converter for d
 java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.logging.log4j.core.pattern.PatternParser.createConverter(PatternParser.java:590)
	at org.apache.logging.log4j.core.pattern.PatternParser.finalizeConverter(PatternParser.java:657)
	at org.apache.logging.log4j.core.pattern.PatternParser.parse(PatternParser.java:420)
	at org.apache.logging.log4j.core.pattern.PatternParser.parse(PatternParser.java:177)
	at org.apache.logging.log4j.core.layout.PatternLayout$SerializerBuilder.build(PatternLayout.java:474)
	at org.apache.logging.log4j.core.layout.PatternLayout.<init>(PatternLayout.java:140)
	at org.apache.logging.log4j.core.layout.PatternLayout.<init>(PatternLayout.java:61)
	at org.apache.logging.log4j.core.layout.PatternLayout$Builder.build(PatternLayout.java:770)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.setToDefault(AbstractConfiguration.java:723)
	at org.apache.logging.log4j.core.config.DefaultConfiguration.<init>(DefaultConfiguration.java:47)
	at org.apache.logging.log4j.core.LoggerContext.<init>(LoggerContext.java:95)
	at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.createContext(ClassLoaderContextSelector.java:254)
	at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.locateContext(ClassLoaderContextSelector.java:218)
	at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:136)
	at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:123)
	at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:117)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:150)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:47)
	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:196)
	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:599)
	at gov.nist.secauto.scap.validation.Application.<clinit>(Application.java:150)
Caused by: java.lang.Error: java.io.FileNotFoundException: /usr/lib/jvm/java-11-openjdk-11.0.20.0.8-2.el8.x86_64/lib/tzdb.dat (No such file or directory)
	at java.base/sun.util.calendar.ZoneInfoFile$1.run(ZoneInfoFile.java:261)
	at java.base/sun.util.calendar.ZoneInfoFile$1.run(ZoneInfoFile.java:251)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/sun.util.calendar.ZoneInfoFile.<clinit>(ZoneInfoFile.java:251)
	at java.base/sun.util.calendar.ZoneInfo.getTimeZone(ZoneInfo.java:588)
	at java.base/java.util.TimeZone.getTimeZone(TimeZone.java:577)
	at java.base/java.util.TimeZone.setDefaultZone(TimeZone.java:682)
	at java.base/java.util.TimeZone.getDefaultRef(TimeZone.java:653)
	at java.base/java.util.TimeZone.getDefault(TimeZone.java:642)
	at org.apache.logging.log4j.core.util.datetime.FixedDateFormat.createIfSupported(FixedDateFormat.java:461)
	at org.apache.logging.log4j.core.pattern.DatePatternConverter.createFormatter(DatePatternConverter.java:194)
	at org.apache.logging.log4j.core.pattern.DatePatternConverter.<init>(DatePatternConverter.java:183)
	at org.apache.logging.log4j.core.pattern.DatePatternConverter.newInstance(DatePatternConverter.java:208)
	... 25 more
Caused by: java.io.FileNotFoundException: /usr/lib/jvm/java-11-openjdk-11.0.20.0.8-2.el8.x86_64/lib/tzdb.dat (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at java.base/sun.util.calendar.ZoneInfoFile$1.run(ZoneInfoFile.java:255)
	... 37 more
ERROR StatusLogger Unrecognized conversion specifier [d] starting at position 16 in conversion pattern.
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class sun.util.calendar.ZoneInfoFile
	at java.base/sun.util.calendar.ZoneInfo.getTimeZone(ZoneInfo.java:588)
	at java.base/java.util.TimeZone.getTimeZone(TimeZone.java:577)
	at java.base/java.util.TimeZone.setDefaultZone(TimeZone.java:682)
	at java.base/java.util.TimeZone.getDefaultRef(TimeZone.java:653)
	at java.base/java.util.TimeZone.getDefault(TimeZone.java:642)
	at java.base/java.util.Calendar.defaultTimeZone(Calendar.java:1679)
	at java.base/java.util.Calendar.getInstance(Calendar.java:1660)
	at java.base/java.text.SimpleDateFormat.initializeCalendar(SimpleDateFormat.java:676)
	at java.base/java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:620)
	at java.base/sun.net.www.protocol.file.FileURLConnection.initializeHeaders(FileURLConnection.java:129)
	at java.base/sun.net.www.protocol.file.FileURLConnection.getHeaderField(FileURLConnection.java:142)
	at java.base/sun.net.www.protocol.jar.JarURLConnection.getHeaderField(JarURLConnection.java:233)
	at java.base/java.net.URLConnection.getHeaderFieldDate(URLConnection.java:661)
	at java.base/java.net.URLConnection.getLastModified(URLConnection.java:566)
	at org.apache.logging.log4j.core.config.ConfigurationSource.getConfigurationSource(ConfigurationSource.java:378)
	at org.apache.logging.log4j.core.config.ConfigurationSource.fromResource(ConfigurationSource.java:356)
	at org.apache.logging.log4j.core.config.ConfigurationFactory$Factory.getConfiguration(ConfigurationFactory.java:552)
	at org.apache.logging.log4j.core.config.ConfigurationFactory$Factory.getConfiguration(ConfigurationFactory.java:481)
	at org.apache.logging.log4j.core.config.ConfigurationFactory.getConfiguration(ConfigurationFactory.java:323)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:695)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:716)
	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:270)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:155)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:47)
	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:196)
	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:599)
	at gov.nist.secauto.scap.validation.Application.<clinit>(Application.java:150)
```

#### Expected Results:

No errors

**Comment by Mab879** [comment]
I was unable reproduce this on a RHEL 8.8 VM. Based on the error messages it looks the Java install was not fully functional.

**Comment by marcusburghardt** [comment]
Thanks for trying to reproduce @Mab879 . I didn't investigate this too much but only tried to re-trigger the test some times and the error persisted. Maybe it is related to the test environment. Let's monitor the next round of tests.

**Comment by mildas** [comment]
@Mab879 Can you try it on latest nightly 8.9 compose?

**Comment by mildas** [comment]
Passed in two last productization runs. Closing
