### ISSUE TITLE
SCE script not included in datastream when using complex-check

### ISSUE THREAD

**Issue by a-skr** [ComplianceAsCode/content#11681]
#### Description of problem:

This issue is related to the guide generation tool-chain.

When adding a SCE script on a rule that already contains an OVAL rule, if the SCE script uses a complex-check, the SCE script is not included in the data-stream.

#### SCAP Security Guide Version:

current / master.

#### Operating System Version:

Issue has been observed on Debian 12 and Ubuntu 22.04. I cannot tell for other operating systems (but the issue is likely present).

#### Steps to Reproduce:

1. Add a `linux_os/guide/system/permissions/files/file_permissions_unauthorized_sgid/sce/shared.sh` file with the following content:

```bash
#! /bin/bash
# platform = multi_platform_all
# check-import = stdout
# complex-check = OR

echo "HELLO_THIS_IS_MY_TEST"

exit ${XCCDF_RESULT_PASS}
```

2. Build any guide that includes the file_permissions_unauthorized_sgid rule

> note: an full example is available on [https://github.com/a-skr/content.git]( https://github.com/a-skr/content.git) on the `issue-oval-sce` branch. To build the guide, use the following command:

    ADDITIONAL_CMAKE_OPTIONS="-DSSG_SCE_ENABLED:BOOL=ON" ./build_product debian12

Then,

    grep HELLO ssg-debian12-ds.xml

returns nothing.

#### Actual Results:

The script is not included in the data-stream file.

#### Expected Results:

The script shall be included in the data-stream file.

#### Additional Information/Debugging Steps:

If the complex-check is omitted, the script is included in the datastream file.

> note: dodys has confirmed the issue on gitter.

**Comment by dodys** [comment]
just to add more information, the same happen with `# complex-check = AND`.
Just the mere presence of it causes this issue independent for the value assigned.

**Comment by cipherboy** [comment]
I can fix this one. :-)

**Comment by dodys** [comment]
it seems the fix for this actually created an issue:

```
[9/19] [ubuntu2204-content] generating plain XCCDF, OVAL and OCIL files
FAILED: ubuntu2204/ssg-ubuntu2204-xccdf.xml ubuntu2204/ssg-ubuntu2204-oval.xml ubuntu2204/ssg-ubuntu2204-ocil.xml /home/ubuntu/git-pulls/usg/CaC-upstream/build/ubuntu2204/ssg-ubuntu2204-xccdf.xml /home/ubuntu/git-pulls/usg/CaC-upstream/build/ubuntu2204/ssg-ubuntu2204-oval.xml /home/ubuntu/git-pulls/usg/CaC-upstream/build/ubuntu2204/ssg-ubuntu2204-ocil.xml 
cd /home/ubuntu/git-pulls/usg/CaC-upstream/build/ubuntu2204 && env PYTHONPATH=/home/ubuntu/git-pulls/usg/CaC-upstream::/home/ubuntu/git-pulls/ubuntu-cve-tracker/scripts /usr/bin/python3 /home/ubuntu/git-pulls/usg/CaC-upstream/build-scripts/build_xccdf.py --build-ovals-dir /home/ubuntu/git-pulls/usg/CaC-upstream/build/ubuntu2204/checks/oval --resolved-base /home/ubuntu/git-pulls/usg/CaC-upstream/build/ubuntu2204 --build-config-yaml /home/ubuntu/git-pulls/usg/CaC-upstream/build/build_config.yml --product-yaml /home/ubuntu/git-pulls/usg/CaC-upstream/build/ubuntu2204/product.yml --xccdf /home/ubuntu/git-pulls/usg/CaC-upstream/build/ubuntu2204/ssg-ubuntu2204-xccdf.xml --oval /home/ubuntu/git-pulls/usg/CaC-upstream/build/ubuntu2204/ssg-ubuntu2204-oval.xml --ocil /home/ubuntu/git-pulls/usg/CaC-upstream/build/ubuntu2204/ssg-ubuntu2204-ocil.xml --thin-ds-components-dir off && sync
Traceback (most recent call last):
  File "/home/ubuntu/git-pulls/usg/CaC-upstream/build-scripts/build_xccdf.py", line 148, in <module>
    main()
  File "/home/ubuntu/git-pulls/usg/CaC-upstream/build-scripts/build_xccdf.py", line 131, in main
    oval_linker = link_oval(xccdftree, checks, args.oval, args.build_ovals_dir)
  File "/home/ubuntu/git-pulls/usg/CaC-upstream/build-scripts/build_xccdf.py", line 76, in link_oval
    oval_linker.link()
  File "/home/ubuntu/git-pulls/usg/CaC-upstream/ssg/build_renumber.py", line 180, in link
    self._link_oval_tree()
  File "/home/ubuntu/git-pulls/usg/CaC-upstream/ssg/build_renumber.py", line 202, in _link_oval_tree
    self._ensure_by_xccdf_referenced_oval_def_is_defined_in_oval_file()
  File "/home/ubuntu/git-pulls/usg/CaC-upstream/ssg/build_renumber.py", line 279, in _ensure_by_xccdf_referenced_oval_def_is_defined_in_oval_file
    rule.remove(check)
ValueError: list.remove(x): x not in list
ninja: build stopped: subcommand failed.
```

This only happens when `# complex-check` is present in a SCE script

**Comment by dodys** [comment]
For some reason this is not happening when building on a newer Ubuntu version, I wonder if that's python incompatibility
Nevertheless the fix doesn't solve the SCE issue, the scripts are still not being include in the datastream. And now it even doesn't matter if the complex-check is there or not. They are simply not added altogether.

**Comment by cipherboy** [comment]
@dodys I'm running Python 3.12.2 on Fedora 39 at the moment, so I definitely have a very new Python interpreter.

When pulling @a-skr's commit on top of `main` (bcc8c93f02dfe93bccf031309338b82b0231989b) and building, I get no error:

```
$ ADDITIONAL_CMAKE_OPTIONS="-DSSG_SCE_ENABLED:BOOL=ON -DSSG_JINJA2_CACHE_DIR=$SSG_JINJA2_CACHE_DIR" ./build_product -j99 debian12
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- SCAP Security Guide 0.1.73
-- (see /home/cipherboy/GitHub/ComplianceAsCode/content/docs/manual/developer_guide.adoc for build instructions)
-- 
CMake Warning (dev) at CMakeLists.txt:148 (find_package):
  Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules
  are removed.  Run "cmake --help-policy CMP0148" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found PythonInterp: /usr/bin/python3 (found version "3.12.2") 
-- Found PY_yaml: /usr/lib64/python3.12/site-packages/yaml  
-- Found PY_jinja2: /home/cipherboy/.local/lib/python3.12/site-packages/jinja2  
-- Found PY_lxml: /usr/lib64/python3.12/site-packages/lxml  
-- Could NOT find PY_pytest (missing: PY_PYTEST) 
-- Could NOT find PY_pytest_cov (missing: PY_PYTEST_COV) 
-- Could NOT find PY_json2html (missing: PY_JSON2HTML) 
-- Could NOT find PY_mypy (missing: PY_MYPY) 
-- Could NOT find PY_openpyxl (missing: PY_OPENPYXL) 
-- Could NOT find PY_pandas (missing: PY_PANDAS) 
-- Could NOT find PY_pcre2 (missing: PY_PCRE2) 
-- Could NOT find PY_cmakelint (missing: PY_CMAKELINT) 
-- Could NOT find PY_sphinx (missing: PY_SPHINX) 
-- Could NOT find PY_sphinxcontrib.autojinja (missing: PY_SPHINXCONTRIB.AUTOJINJA) 
-- Could NOT find PY_sphinx_rtd_theme (missing: PY_SPHINX_RTD_THEME) 
-- Could NOT find PY_myst_parser (missing: PY_MYST_PARSER) 
-- Could NOT find PY_prometheus_client (missing: PY_PROMETHEUS_CLIENT) 
-- Could NOT find PY_trestle (missing: PY_TRESTLE) 
-- Found PY_requests: /usr/lib/python3.12/site-packages/requests  
-- CMake:
-- build type: Release
-- generator: Ninja
-- source directory: /home/cipherboy/GitHub/ComplianceAsCode/content
-- build directory: /home/cipherboy/GitHub/ComplianceAsCode/content/build
-- Logging: OFF
--  
-- Tools:
-- python: /usr/bin/python3 (version: 3.12.2)
-- python yaml module: /usr/lib64/python3.12/site-packages/yaml
-- python jinja2 module: /home/cipherboy/.local/lib/python3.12/site-packages/jinja2
-- oscap: /usr/bin/oscap (version: 1.3.9)
-- xsltproc: /usr/bin/xsltproc
-- xmllint: /usr/bin/xmllint
-- sed: /usr/bin/sed
-- shellcheck (optional): SHELLCHECK_EXECUTABLE-NOTFOUND
-- linkchecker (optional): LINKCHECKER_EXECUTABLE-NOTFOUND
-- grep (optional): /usr/bin/grep
-- python pytest module (optional): 
-- ansible-playbook module (optional): ANSIBLE_PLAYBOOK_EXECUTABLE-NOTFOUND
-- ansible-lint module (optional): ANSIBLE_LINT_EXECUTABLE-NOTFOUND
-- yamllint module (optional): YAMLLINT_EXECUTABLE-NOTFOUND
-- python mypy module (optional): 
-- BATS framework (optional): BATS_EXECUTABLE-NOTFOUND
-- python sphinx module (optional): 
-- python sphinxcontrib.autojinja module (optional): 
-- python sphinx_rtd_theme module (optional): 
-- python myst-parser module (optional): 
-- python openpyxl module (optional): 
-- python pandas module (optional): 
-- python pcre2 module (optional): 
-- python lxml module (optional): /usr/lib64/python3.12/site-packages/lxml
-- python prometheus-client module (optional): 
-- python compliance-trestle module (optional): 
--  
-- Build options:
-- SSG vendor string: ssgproject
-- Target OVAL version: 5.11
-- Build SCAP 1.2 source data streams: ON
-- OVAL schematron validation: ON
-- shellcheck bash fixes validation: ON
-- Separate SCAP files: ON
-- Ansible Playbooks: ON
-- Ansible Playbooks Per Rule: OFF
-- Bash scripts: ON
-- Thin data streams: OFF
-- jinja2 cache: enabled
-- jinja2 cache dir: /home/cipherboy/GitHub/ComplianceAsCode/content/.jinja2-cache
-- STIG Delta Taloring files: ON
-- Build SCE Content: ON
-- SCAPVal 1.3 Enabled: OFF
--  
-- Products:
-- Alibaba Cloud Linux 2: OFF
-- Alibaba Cloud Linux 3: OFF
-- Anolis OS 8: OFF
-- Anolis OS 23: OFF
-- Chromium: OFF
-- Debian 10: OFF
-- Debian 11: OFF
-- Debian 12: ON
-- Example: OFF
-- EKS: OFF
-- Fedora: OFF
-- Firefox: OFF
-- MacOS 1015: OFF
-- OCP4: OFF
-- RHCOS4: OFF
-- Oracle Linux 7: OFF
-- Oracle Linux 8: OFF
-- Oracle Linux 9: OFF
-- openEuler 22.03 LTS: OFF
-- openSUSE: OFF
-- RHEL 7: OFF
-- RHEL 8: OFF
-- RHEL 9: OFF
-- RHEL 10: OFF
-- RHV 4: OFF
-- SUSE 12: OFF
-- SUSE 15: OFF
-- Ubuntu 16.04: OFF
-- Ubuntu 18.04: OFF
-- Ubuntu 20.04: OFF
-- Ubuntu 22.04: OFF
-- Uos 20: OFF
-- OpenEmbedded: OFF
--  
-- Scanning for dependencies of debian12 fixes (bash, ansible, puppet, anaconda, ignition, kubernetes and blueprint)...
-- Configuring done (0.7s)
-- Generating done (0.0s)
-- Build files have been written to: /home/cipherboy/GitHub/ComplianceAsCode/content/build
[19/19] [man-page] generating man page
$ grep 'HELLO' ./build/ssg-debian12-ds-1.2.xml 
echo "HELLO_THIS_IS_MY_TEST"
```

Do you have a commit for me to test with? This one has a check like:

```
#! /bin/bash
# platform = multi_platform_all
# check-import = stdout
# complex-check = OR

echo "HELLO_THIS_IS_MY_TEST"
```

---

That said, the fix was in XPath, which it seems suspicious that it'd be a Python version issue as I doubt xpath's behavior around node traversal and `//` operators has changed... My 2c. but I'd perhaps be inclined to believe there's more bugs running around, given what Matt quoted me as commenting earlier. :D

**Comment by dodys** [comment]
@cipherboy it is truly weird but I finally found it is only happening for rule `all_apparmor_profiles_in_enforce_complain_mode`
if I add the `complex-check` to the SCE. It happens on both versions of Ubuntu and python I tested, therefore I'm ruling out the python version.

**Comment by dodys** [comment]
ok, I don't seem to be able to reproduce it anymore. Not sure what is going on in my environment today. I will just close it for now and let you know otherwise.
