### ISSUE TITLE
RHEL8 STIG fails to apply at RHEL-08-010287

### ISSUE THREAD

**Issue by autobotcoop** [ComplianceAsCode/content#12267]
#### Description of problem:
RHEL8 STIG fails to apply at RHEL-08-010287

#### SCAP Security Guide Version:
0.1.67
#### Operating System Version:
RHEL 8.10
#### Steps to Reproduce:

1. ansible-playbook -i "localhost," -c local playbook.yml 

#### Actual Results:
```
TASK [RedHatOfficial.rhel8_stig : Configure SSH to use System Crypto Policy] ***************************************************************
task path: /root/.ansible/roles/RedHatOfficial.rhel8_stig/tasks/main.yml:2088
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~root && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1722876225.9989052-23309-255711604585471 `" && echo ansible-tmp-1722876225.9989052-23309-255711604585471="` echo /root/.ansible/tmp/ansible-tmp-1722876225.9989052-23309-255711604585471 `" ) && sleep 0'
Using module file /usr/lib/python3.12/site-packages/ansible/modules/lineinfile.py
<localhost> PUT /root/.ansible/tmp/ansible-local-21736l6rcow9_/tmptd1alkms TO /root/.ansible/tmp/ansible-tmp-1722876225.9989052-23309-255711604585471/AnsiballZ_lineinfile.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1722876225.9989052-23309-255711604585471/ /root/.ansible/tmp/ansible-tmp-1722876225.9989052-23309-255711604585471/AnsiballZ_lineinfile.py && sleep 0'
<localhost> EXEC /bin/sh -c '/bin/python3.12 /root/.ansible/tmp/ansible-tmp-1722876225.9989052-23309-255711604585471/AnsiballZ_lineinfile.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1722876225.9989052-23309-255711604585471/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1722876225.9989052-23309-255711604585471/AnsiballZ_lineinfile.py", line 107, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1722876225.9989052-23309-255711604585471/AnsiballZ_lineinfile.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1722876225.9989052-23309-255711604585471/AnsiballZ_lineinfile.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible.modules.lineinfile', init_globals=dict(_module_fqn='ansible.modules.lineinfile', _modlib_path=modlib_path),
  File "<frozen runpy>", line 226, in run_module
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "/tmp/ansible_lineinfile_payload_ha37eyoq/ansible_lineinfile_payload.zip/ansible/modules/lineinfile.py", line 638, in <module>
  File "/tmp/ansible_lineinfile_payload_ha37eyoq/ansible_lineinfile_payload.zip/ansible/modules/lineinfile.py", line 634, in main
  File "/tmp/ansible_lineinfile_payload_ha37eyoq/ansible_lineinfile_payload.zip/ansible/modules/lineinfile.py", line 528, in absent
  File "/usr/lib64/python3.12/re/__init__.py", line 228, in compile
    return _compile(pattern, flags)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/re/__init__.py", line 307, in _compile
    p = _compiler.compile(pattern, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/re/_compiler.py", line 745, in compile
    p = _parser.parse(p, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/re/_parser.py", line 979, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/re/_parser.py", line 460, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/re/_parser.py", line 840, in _parse
    raise source.error('global flags not at the start '
re.error: global flags not at the start of the expression at position 4
fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1722876225.9989052-23309-255711604585471/AnsiballZ_lineinfile.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1722876225.9989052-23309-255711604585471/AnsiballZ_lineinfile.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1722876225.9989052-23309-255711604585471/AnsiballZ_lineinfile.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.lineinfile', init_globals=dict(_module_fqn='ansible.modules.lineinfile', _modlib_path=modlib_path),\n  File \"<frozen runpy>\", line 226, in run_module\n  File \"<frozen runpy>\", line 98, in _run_module_code\n  File \"<frozen runpy>\", line 88, in _run_code\n  File \"/tmp/ansible_lineinfile_payload_ha37eyoq/ansible_lineinfile_payload.zip/ansible/modules/lineinfile.py\", line 638, in <module>\n  File \"/tmp/ansible_lineinfile_payload_ha37eyoq/ansible_lineinfile_payload.zip/ansible/modules/lineinfile.py\", line 634, in main\n  File \"/tmp/ansible_lineinfile_payload_ha37eyoq/ansible_lineinfile_payload.zip/ansible/modules/lineinfile.py\", line 528, in absent\n  File \"/usr/lib64/python3.12/re/__init__.py\", line 228, in compile\n    return _compile(pattern, flags)\n           ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib64/python3.12/re/__init__.py\", line 307, in _compile\n    p = _compiler.compile(pattern, flags)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib64/python3.12/re/_compiler.py\", line 745, in compile\n    p = _parser.parse(p, flags)\n        ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib64/python3.12/re/_parser.py\", line 979, in parse\n    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib64/python3.12/re/_parser.py\", line 460, in _parse_sub\n    itemsappend(_parse(source, state, verbose, nested + 1,\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib64/python3.12/re/_parser.py\", line 840, in _parse\n    raise source.error('global flags not at the start '\nre.error: global flags not at the start of the expression at position 4\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}


```

#### Expected Results:

STIG Applied

**Comment by autobotcoop** [comment]
Fixed the bad regex line in the playbbok but new error:

```
[localhost] (item=[{'key': 'jlayton', 'value': ['x', '1000', '1000', 'Jeff Layton', '/home/jlayton', '/bin/bash']}, {'changed': False, 'stat': {'exists': True, 'path': '/home/jlayton', 'mode': '0700', 'isdir': True, 'ischr': False, 'isblk': False, 'isreg': False, 'isfifo': False, 'islnk': False, 'issock': False, 'uid': 1000, 'gid': 1000, 'size': 4096, 'inode': 131, 'dev': 64773, 'nlink': 27, 'atime': 1722875208.6223545, 'mtime': 1722874512.0373023, 'ctime': 1722874512.0373023, 'wusr': True, 'rusr': True, 'xusr': True, 'wgrp': False, 'rgrp': False, 'xgrp': False, 'woth': False, 'roth': False, 'xoth': False, 'isuid': False, 'isgid': False, 'blocks': 8, 'block_size': 4096, 'device_type': 0, 'readable': True, 'writeable': True, 'executable': True, 'pw_name': 'jlayton', 'gr_name': 'jlayton', 'mimetype': 'inode/directory', 'charset': 'binary', 'version': '2377195826', 'attributes': [], 'attr_flags': ''}, 'invocation': {'module_args': {'path': '/home/jlayton', 'follow': False, 'get_checksum': True, 'get_mime': True, 'get_attributes': True, 'checksum_algorithm': 'sha1'}}, 'failed': False, 'item': {'key': 'jlayton', 'value': ['x', '1000', '1000', 'Jeff Layton', '/home/jlayton', '/bin/bash']}, 'ansible_loop_var': 'item'}]) => {"ansible_loop_var": "item", "changed": false, "gid": 0, "group": "root", "item": [{"key": "jlayton", "value": ["x", "1000", "1000", "Jeff Layton", "/home/jlayton", "/bin/bash"]}, {"ansible_loop_var": "item", "changed": false, "failed": false, "invocation": {"module_args": {"checksum_algorithm": "sha1", "follow": false, "get_attributes": true, "get_checksum": true, "get_mime": true, "path": "/home/jlayton"}}, "item": {"key": "jlayton", "value": ["x", "1000", "1000", "Jeff Layton", "/home/jlayton", "/bin/bash"]}, "stat": {"atime": 1722875208.6223545, "attr_flags": "", "attributes": [], "block_size": 4096, "blocks": 8, "charset": "binary", "ctime": 1722874512.0373023, "dev": 64773, "device_type": 0, "executable": true, "exists": true, "gid": 1000, "gr_name": "jlayton", "inode": 131, "isblk": false, "ischr": false, "isdir": true, "isfifo": false, "isgid": false, "islnk": false, "isreg": false, "issock": false, "isuid": false, "mimetype": "inode/directory", "mode": "0700", "mtime": 1722874512.0373023, "nlink": 27, "path": "/home/jlayton", "pw_name": "jlayton", "readable": true, "rgrp": false, "roth": false, "rusr": true, "size": 4096, "uid": 1000, "version": "2377195826", "wgrp": false, "woth": false, "writeable": true, "wusr": true, "xgrp": false, "xoth": false, "xusr": true}}], "mode": "0644", "msg": "chgrp failed", "owner": "root", "path": "/snap/code/164/usr/share/glib-2.0/schemas/org.gnome.desktop.a11y.applications.gschema.xml", "secontext": "system_u:object_r:snappy_snap_t:s0", "size": 845, "state": "file", "uid": 0}
-bash: syntax error near unexpected token `('
```

**Comment by autobotcoop** [comment]
Fixed it after deleting /home/jlayton/snap
