### ISSUE TITLE
Tracebacks in RHEL6 builds

### ISSUE THREAD

**Issue by jan-cerny** [ComplianceAsCode/content#4025]
#### Description of problem:
There are tracebacks in RHEL6 builds but the test pass.

#### SCAP Security Guide Version:
current upstream head as of 27th February

#### Operating System Version:
RHEL6

#### Steps to Reproduce:

1. build on RHEL6
2.
3.
4.

#### Actual Results:
```
Fatal error encountered when generating role '/home/jenkins/workspace/scap-security-guide-pull-requests/label/rhel6/build/roles/ssg-ol8-role-cjis.yml'. Error details:
sub() got an unexpected keyword argument 'flags'

Exception in thread Role generate worker #1:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.6/threading.py", line 484, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/jenkins/workspace/scap-security-guide-pull-requests/label/rhel6/build-scripts/build_all_remediation_roles.py", line 94, in <lambda>
    target=lambda queue=queue: ssg.build_roles.builder(queue)
  File "/home/jenkins/workspace/scap-security-guide-pull-requests/label/rhel6/ssg/build_roles.py", line 141, in builder
    raise error
TypeError: sub() got an unexpected keyword argument 'flags'

Fatal error encountered when generating role '/home/jenkins/workspace/scap-security-guide-pull-requests/label/rhel6/build/roles/ssg-ol8-role-hipaa.yml'. Error details:
sub() got an unexpected keyword argument 'flags'

Exception in thread Role generate worker #0:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.6/threading.py", line 484, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/jenkins/workspace/scap-security-guide-pull-requests/label/rhel6/build-scripts/build_all_remediation_roles.py", line 94, in <lambda>
    target=lambda queue=queue: ssg.build_roles.builder(queue)
  File "/home/jenkins/workspace/scap-security-guide-pull-requests/label/rhel6/ssg/build_roles.py", line 141, in builder
    raise error
TypeError: sub() got an unexpected keyword argument 'flags'
```

#### Expected Results:
no traceback, every artifact is build correctly

#### Addition Information/Debugging Steps:
Happend on Jenkins, eg. https://jenkins.complianceascode.io/job/scap-security-guide-pull-requests/690/label=rhel6/console

**Comment by ggbecker** [comment]
Still happening:
```
Traceback (most recent call last):
  File "/usr/lib64/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.6/threading.py", line 484, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/jenkins/workspace/scap-security-guide-pull-requests/label/rhel6/build-scripts/build_profile_remediations.py", line 103, in <lambda>
    target=lambda queue=queue: ssg.build_profile_remediations.builder(queue)
  File "/home/jenkins/workspace/scap-security-guide-pull-requests/label/rhel6/ssg/build_profile_remediations.py", line 145, in builder
    raise error
TypeError: sub() got an unexpected keyword argument 'flags'
```
https://jenkins.complianceascode.io/job/scap-security-guide-pull-requests/1339/label=rhel6/console

**Comment by Mab879** [comment]
RHEL6 is EOL. Closing, please re-open if needed.
