### ISSUE TITLE
Issue building RHV4 on Ubuntu 20.10

### ISSUE THREAD

**Issue by cipherboy** [ComplianceAsCode/content#6875]
#### Description of problem:

RHV4 fails to build for me on Ubuntu 20.10

```
cd /home/cipherboy/GitHub/cipherboy/scap-security-guide/build/rhv4 && /usr/bin/cmake -E remove_directory /home/cipherboy/GitHub/cipherboy/scap-security-guide/build/rhv4/rules && env PYTHONPATH=/home/cipherboy/GitHub/cipherboy/scap-security-guide /usr/bin/python3 /home/cipherboy/GitHub/cipherboy/scap-security-guide/build-scripts/yaml_to_shorthand.py --resolved-rules-dir /home/cipherboy/GitHub/cipherboy/scap-security-guide/build/rhv4/rules --build-config-yaml /home/cipherboy/GitHub/cipherboy/scap-security-guide/build/build_config.yml --product-yaml /home/cipherboy/GitHub/cipherboy/scap-security-guide/rhv4/product.yml --bash-remediation-fns /home/cipherboy/GitHub/cipherboy/scap-security-guide/build/bash-remediation-functions.xml --profiles-root /home/cipherboy/GitHub/cipherboy/scap-security-guide/build/rhv4/profiles --output /home/cipherboy/GitHub/cipherboy/scap-security-guide/build/rhv4/shorthand.xml && /usr/bin/xmllint --format --output /home/cipherboy/GitHub/cipherboy/scap-security-guide/build/rhv4/shorthand.xml /home/cipherboy/GitHub/cipherboy/scap-security-guide/build/rhv4/shorthand.xml
Traceback (most recent call last):
  File "/home/cipherboy/GitHub/cipherboy/scap-security-guide/build-scripts/yaml_to_shorthand.py", line 83, in <module>
    main()
  File "/home/cipherboy/GitHub/cipherboy/scap-security-guide/build-scripts/yaml_to_shorthand.py", line 75, in main
    p.validate_rules(loader.all_rules, loader.all_groups)
  File "/home/cipherboy/GitHub/cipherboy/scap-security-guide/ssg/build_yaml.py", line 355, in validate_rules
    raise ValueError(msg)
ValueError: Rule 'dconf_db_up_to_date' was not found in the benchmark. Please remove rule 'dconf_db_up_to_date' from profile 'pci-dss' before proceeding.
```

Looks like it is missing from the prodtype:

```
prodtype: fedora,ol7,ol8,rhel7,rhel8,sle12,sle15
```

Is rhv4 supposed to inherit from rhel?

#### SCAP Security Guide Version:

commit 23234542ced16a380f4d24de96c368cac12922ca (upstream/master, origin/master, origin/HEAD, master)
Merge: 82dacab7c ec1f53013
Author: Watson Yuuma Sato <wsato@redhat.com>
Date:   Wed Apr 21 16:52:22 2021 +0200

    Merge pull request #6851 from freddieRv/OL-cjis-profiles
    
    Ol cjis profiles

#### Operating System Version:

Ubuntu 20.10

```
OpenSCAP command line tool (oscap) 1.2.17
Copyright 2009--2017 Red Hat Inc., Durham, North Carolina.

==== Supported specifications ====
XCCDF Version: 1.2
OVAL Version: 5.11.1
CPE Version: 2.3
CVSS Version: 2.0
CVE Version: 2.0
Asset Identification Version: 1.1
Asset Reporting Format Version: 1.1
CVRF Version: 1.1
```

#### Steps to Reproduce:

1. ./build_product rhv4

#### Actual Results:
Build fails, see above message.

#### Expected Results:

Build succeeds.

**Comment by cipherboy** [comment]
Also happened on F32.
