### ISSUE TITLE
SSGTS combined mode - 'list' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by mildas** [ComplianceAsCode/content#7359]
#### Description of problem:
SSGTS in combined mode is terminated by exception:
```
INFO - The base image option has not been specified, choosing libvirt-based test environment.
INFO - Logging into /tmp/tmp.V2uBZwYurK/logs/combined-custom-2021-08-07-1151/test_suite.log
Setting console output to log level INFO
Traceback (most recent call last):
  File "/tmp/tmp.V2uBZwYurK/rpmbuild/BUILD/scap-security-guide-0.1.58/tests/test_suite.py", line 396, in <module>
    main()
  File "/tmp/tmp.V2uBZwYurK/rpmbuild/BUILD/scap-security-guide-0.1.58/tests/test_suite.py", line 392, in main
    options.func(options)
  File "/tmp/tmp.V2uBZwYurK/rpmbuild/BUILD/scap-security-guide-0.1.58/tests/ssg_test_suite/combined.py", line 101, in perform_combined_check
    if not profile.startswith(OSCAP_PROFILE):
AttributeError: 'list' object has no attribute 'startswith'
```

#### SCAP Security Guide Version:
a4e6221

#### Steps to Reproduce:

1. `python3 tests/test_suite.py combined --libvirt qemu:///system test_suite_rhel85 --datastream build/ssg-rhel8-ds.xml                 --mode online --remediate-using bash xccdf_org.ssgproject.content_profile_ospp`

#### Actual Results:
Exception

#### Expected Results:
No exception

**Comment by ggbecker** [comment]
This was fixed by #7310
