### ISSUE TITLE
SSGTS combined mode - 'CombinedChecker' object has no attribute 'run_aborted'

### ISSUE THREAD

**Issue by mildas** [ComplianceAsCode/content#7512]
#### Description of problem:
SSGTS in combined mode throws:
```
INFO - xccdf_org.ssgproject.content_rule_accounts_passwords_pam_faillock_deny
INFO - Script config_without_skip.pass.sh using profile (all) OK
INFO - Script default_die_pam_unix.fail.sh using profile (all) OK
ERROR - Failed to execute 'cd /root/ssgts/accounts_passwords_pam_faillock_deny; SHARED=/root/ssgts/shared bash -x disablefaillock_authconfig.fail.sh' on root@192.168.122.247: Command '('ssh', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', '-o', 'IdentityFile=/root/.ssh/ssg_id_ecdsa', 'root@192.168.122.247', 'cd /root/ssgts/accounts_passwords_pam_faillock_deny; SHARED=/root/ssgts/shared bash -x disablefaillock_authconfig.fail.sh')' returned non-zero exit status 127.
ERROR - Terminating due to error: Failed to execute 'cd /root/ssgts/accounts_passwords_pam_faillock_deny; SHARED=/root/ssgts/shared bash -x disablefaillock_authconfig.fail.sh' on root@192.168.122.247.
Setting console output to log level INFO
Traceback (most recent call last):
  File "/tmp/tmp.MECr0QDzb0/rpmbuild/BUILD/scap-security-guide-0.1.58/tests/test_suite.py", line 407, in <module>
    main()
  File "/tmp/tmp.MECr0QDzb0/rpmbuild/BUILD/scap-security-guide-0.1.58/tests/test_suite.py", line 403, in main
    options.func(options)
  File "/tmp/tmp.MECr0QDzb0/rpmbuild/BUILD/scap-security-guide-0.1.58/tests/ssg_test_suite/combined.py", line 120, in perform_combined_check
    if checker.run_aborted:
AttributeError: 'CombinedChecker' object has no attribute 'run_aborted'
```

#### SCAP Security Guide Version:
4a6cf40

#### Operating System Version:
RHEL 8

#### Steps to Reproduce:

1. `python3 /tmp/tmp.MECr0QDzb0/rpmbuild/BUILD/scap-security-guide-0.1.58/tests/test_suite.py combined --libvirt qemu:///system test_suite_vm --datastream /usr/share/xml/scap/ssg/content/ssg-rhel8-ds.xml --mode online                 --remediate-using bash xccdf_org.ssgproject.content_profile_ospp`

#### Actual Results:
exception

#### Expected Results:
no exception

**Comment by Mab879** [comment]
Should be resolved by #7614 once we merge `stabilization` into `master`.
