### ISSUE TITLE
RHEL7 w/Python3 build issue due to Unicode ordinals and default ascii encoding on open()

### ISSUE THREAD

**Issue by lenox-joseph** [ComplianceAsCode/content#7896]
#### Description of problem:
On RHEL7, building the SSG fail with Python 3.6.8 due to defaulting to `ascii` codec at the following points:
```
  File "/tti/home/jdlenox/scap-security-guide/utils/gen_multiple_reference_tables.py", line 45, in <module>
    outfile.write(result)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2019' in position 145690: ordinal not in range(128)
Traceback (most recent call last):
  File "/tti/home/jdlenox/scap-security-guide/utils/gen_profile_table.py", line 70, in <module>
    renderer.output_results(args)
  File "/tti/home/jdlenox/scap-security-guide/utils/template_renderer.py", line 110, in output_results
    outfile.write(result)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2019' in position 138322: ordinal not in range(128)
```

#### SCAP Security Guide Version:
99a466d091775a42316cb95fc326b9eb600261e9

#### Operating System Version:
RHEL 7.9 (Maipo)

#### Steps to Reproduce:

1. Set up a RHEL7 system with `python3` installed from yum and the rest of the dependencies (`jinja`) with pip
2. Build the RHEL7 targets with cmake.

#### Actual Results:
```
  File "/tti/home/jdlenox/scap-security-guide/utils/gen_multiple_reference_tables.py", line 45, in <module>
    outfile.write(result)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2019' in position 145690: ordinal not in range(128)
Traceback (most recent call last):
  File "/tti/home/jdlenox/scap-security-guide/utils/gen_profile_table.py", line 70, in <module>
    renderer.output_results(args)
  File "/tti/home/jdlenox/scap-security-guide/utils/template_renderer.py", line 110, in output_results
    outfile.write(result)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2019' in position 138322: ordinal not in range(128)
```

#### Expected Results:
SSG builds without error.

#### Additional Information/Debugging Steps:
Adding an explicit `encoding='utf-8'` to the preceeding `open()` calls avoids the issue.

**Comment by Mab879** [comment]
@lenox-joseph can you please try with 2715e8d7009884c198d7a3fc9a291e367d2375e2 or later? That issue should hopefully be fixed.

**Comment by lenox-joseph** [comment]
I'll rebase and give it a  try.

**Comment by lenox-joseph** [comment]
Seems to be fine on this configuration.

**Comment by yuumasato** [comment]
Thanks for checking!
