### ISSUE TITLE
The test_suite.py doesn't work with python 3.6.8

### ISSUE THREAD

**Issue by yuumasato** [ComplianceAsCode/content#8045]
#### Description of problem:

When running the SSGTS with python 3.6.8, the traceback bellow is reported.

#### SCAP Security Guide Version:
stabilization-0.1.60

#### Operating System Version:
RHEL 8.5

#### Actual Results:
```::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
::   Test crypto policy rules
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

:: [ 17:13:10 ] :: [  BEGIN   ] :: Running 'python3 /tmp/tmp.YNloVJEywj/rpmbuild/BUILD/scap-security-guide-0.1.60/tests/test_suite.py rule --mode online             --remediate-using oscap --container ssg_test_suite --datastream /usr/share/xml/scap/ssg/content/ssg-rhel8-ds.xml             --xccdf-id scap_org.open-scap_cref_ssg-rhel8-xccdf-1.2.xml --no-reports configure_crypto_policy configure_bind_crypto_policy configure_kerberos_crypto_policy configure_openssl_crypto_policy configure_libreswan_crypto_policy configure_ssh_crypto_policy'
Setting console output to log level INFO
Traceback (most recent call last):
  File "/tmp/tmp.YNloVJEywj/rpmbuild/BUILD/scap-security-guide-0.1.60/tests/test_suite.py", line 462, in <module>
    main()
  File "/tmp/tmp.YNloVJEywj/rpmbuild/BUILD/scap-security-guide-0.1.60/tests/test_suite.py", line 431, in main
    normalize_passed_arguments(options)
  File "/tmp/tmp.YNloVJEywj/rpmbuild/BUILD/scap-security-guide-0.1.60/tests/test_suite.py", line 390, in normalize_passed_arguments
    options.scanning_mode, options.container)
  File "/tmp/tmp.YNloVJEywj/rpmbuild/BUILD/scap-security-guide-0.1.60/tests/ssg_test_suite/test_env.py", line 469, in __init__
    super(PodmanTestEnv, self).__init__(scanning_mode, image_name)
  File "/tmp/tmp.YNloVJEywj/rpmbuild/BUILD/scap-security-guide-0.1.60/tests/ssg_test_suite/test_env.py", line 271, in __init__
    super(ContainerTestEnv, self).__init__(scanning_mode)
  File "/tmp/tmp.YNloVJEywj/rpmbuild/BUILD/scap-security-guide-0.1.60/tests/ssg_test_suite/test_env.py", line 75, in __init__
    p = subprocess.run(['arf-to-graph', '--version'], capture_output=True)
  File "/usr/lib64/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'capture_output'
:: [ 17:13:11 ] :: [   FAIL   ] :: Command 'python3 /tmp/tmp.YNloVJEywj/rpmbuild/BUILD/scap-security-guide-0.1.60/tests/test_suite.py rule --mode online             --remediate-using oscap --container ssg_test_suite --datastream /usr/share/xml/scap/ssg/content/ssg-rhel8-ds.xml             --xccdf-id scap_org.open-scap_cref_ssg-rhel8-xccdf-1.2.xml --no-reports configure_crypto_policy configure_bind_crypto_policy configure_kerberos_crypto_policy configure_openssl_crypto_policy configure_libreswan_crypto_policy configure_ssh_crypto_policy' (Expected 0, got 1)
:: [ 17:13:11 ] :: [   PASS   ] :: File '/var/tmp/rlRun_LOG.ZgZ4rJ0o' should not contain '^ERROR' 
```

#### Expected Results:
The test suite works.

#### Additional Information/Debugging Steps:
`capture_output` was added in python 3.7
https://docs.python.org/3/library/subprocess.html#using-the-subprocess-module

Related to https://github.com/ComplianceAsCode/content/pull/7750/files#diff-1c3c5ab67800bbd31b63bfa92a7989eb256cf2abd9af2a9ff8acb7efd3c95716R74

**Comment by yuumasato** [comment]
@matejak CC
