### ISSUE TITLE
`utils/compare_ds.py` doesn't work when comparing DS with PCIDSS benchmark and DS without it

### ISSUE THREAD

**Issue by mildas** [ComplianceAsCode/content#8361]
#### Description of problem:
On RHEL 7, `utils/compare_ds.py` fails when comparing 2 DSs and only one of them has `xccdf_org.ssgproject.content_benchmark_PCIDSS-RHEL-7` benchmark.

#### SCAP Security Guide Version:
ece8437

#### Operating System Version:
RHEL 7.9

#### Steps to Reproduce:
1. `PYTHONPATH=/root/content content/utils/compare_ds.py --only-rules usr/share/xml/scap/ssg/content/ssg-rhel7-ds.xml /usr/share/xml/scap/ssg/content/ssg-rhel7-ds.xml`

#### Actual Results:
```
Traceback (most recent call last):
  File "content/utils/compare_ds.py", line 428, in <module>
    sys.exit(main())
  File "content/utils/compare_ds.py", line 423, in main
    args.rule, not args.no_diffs, args.only_rules)
  File "content/utils/compare_ds.py", line 342, in process_benchmarks
    new_rule = new_benchmark.find(
AttributeError: 'NoneType' object has no attribute 'find'
```

#### Expected Results:
Diff is printed.

#### Additional Information/Debugging Steps:
I've used 0.1.57 RHEL7 datastream as `OLD_DS` and RHEL 7 datastream built from upstream master branch as `NEW_DS`.

**Comment by mildas** [comment]
Fixed by #8362
