### ISSUE TITLE
Automatus CI `TypeError: __init__() missing 2 required positional arguments: 'platforms_dir' and 'cpe_items_dir'`

### ISSUE THREAD

**Issue by mildas** [ComplianceAsCode/content#9752]
#### Description of problem:
Automatus in CI traceback:
```
Traceback (most recent call last):
  File "/home/runner/work/content/content/tests/automatus.py", line 502, in <module>
    main()
  File "/home/runner/work/content/content/tests/automatus.py", line 498, in main
    options.func(options)
  File "/home/runner/work/content/content/tests/ssg_test_suite/rule.py", line 669, in perform_rule_check
    checker.test_target()
  File "/home/runner/work/content/content/tests/ssg_test_suite/oscap.py", line 699, in test_target
    self._test_target()
  File "/home/runner/work/content/content/tests/ssg_test_suite/rule.py", line 449, in _test_target
    test_content_by_rule_id = self._get_test_content_by_rule_id(
  File "/home/runner/work/content/content/tests/ssg_test_suite/rule.py", line 435, in _get_test_content_by_rule_id
    rule_test_content = self._get_rule_test_content(rule)
  File "/home/runner/work/content/content/tests/ssg_test_suite/rule.py", line 417, in _get_rule_test_content
    all_tests = self._load_all_tests(rule)
  File "/home/runner/work/content/content/tests/ssg_test_suite/rule.py", line 394, in _load_all_tests
    template_builder = ssg.templates.Builder(
TypeError: __init__() missing 2 required positional arguments: 'platforms_dir' and 'cpe_items_dir'
Error: Process completed with exit code 1.
```
https://github.com/ComplianceAsCode/content/actions/runs/3372700322/jobs/5596508651

#### SCAP Security Guide Version:
master

#### Steps to Reproduce:
So far I was not able to reproduce it locally.

#### Actual Results:
Traceback

#### Expected Results:
No traceback

#### Additional Information/Debugging Steps:
Problematic commit 422df0a4316

**Comment by yuumasato** [comment]
Blocker label added, as this prevents any testing with Automatus.
