### ISSUE TITLE
CTest fails on RHEL7

### ISSUE THREAD

**Issue by matusmarhefka** [ComplianceAsCode/content#9948]
#### Description of problem:
Following (CTest) tests fail on RHEL-7.9:
```
The following tests FAILED:
	 60 - test-compare_ds (Failed)
	 64 - test-controleval-directory (Failed)
	 65 - test-controleval-onefile (Failed)
	 66 - test-controleval-json (Failed)
Errors while running CTest
gmake[1]: *** [test] Error 8
```

#### SCAP Security Guide Version:
master (tested on commit e7502af)

#### Operating System Version:
RHEL-7.9

#### Steps to Reproduce:
1. Run CTest

#### Actual Results:
```
 60/102 Test  #60: test-compare_ds ....................................................***Failed    0.06 sec
Traceback (most recent call last):
  File "/root/rpmbuild/BUILD/scap-security-guide-0.1.66/utils/compare_ds.py", line 6, in <module>
    from ssg.content_diff import StandardContentDiffer, StigContentDiffer
  File "/root/rpmbuild/BUILD/scap-security-guide-0.1.66/ssg/content_diff.py", line 7, in <module>
    import xml.etree.ElementTree as ET
ImportError: No module named etree.ElementTree
...
 64/102 Test  #64: test-controleval-directory .........................................***Failed    0.02 sec
  File "/root/rpmbuild/BUILD/scap-security-guide-0.1.66/utils/controleval.py", line 31
    raise RuntimeError(msg) from e
                               ^
SyntaxError: invalid syntax

        Start  65: test-controleval-onefile
 65/102 Test  #65: test-controleval-onefile ...........................................***Failed    0.02 sec
  File "/root/rpmbuild/BUILD/scap-security-guide-0.1.66/utils/controleval.py", line 31
    raise RuntimeError(msg) from e
                               ^
SyntaxError: invalid syntax

        Start  66: test-controleval-json
 66/102 Test  #66: test-controleval-json ..............................................***Failed    0.01 sec
  File "/root/rpmbuild/BUILD/scap-security-guide-0.1.66/utils/controleval.py", line 31
    raise RuntimeError(msg) from e
                               ^
SyntaxError: invalid syntax
```

#### Expected Results:
no failing tests

**Comment by mildas** [comment]
```
The following tests FAILED:
	 60 - test-compare_ds (Failed)
	 64 - test-controleval-directory (Failed)
	 65 - test-controleval-onefile (Failed)
	 66 - test-controleval-json (Failed)
	 67 - refchecker-rhel8-cis_workstation_l1 (Failed)
	 68 - refchecker-rhel8-cis_workstation_l2 (Failed)
	 69 - refchecker-rhel8-cis_server_l1 (Failed)
	 70 - refchecker-rhel8-cis (Failed)
	 71 - refchecker-rhel7-cis_workstation_l1 (Failed)
	 72 - refchecker-rhel7-cis_workstation_l2 (Failed)
	 73 - refchecker-rhel7-cis_server_l1 (Failed)
	 74 - refchecker-rhel7-cis (Failed)
```
but it's still the same - `etree.ElementTree` and invalid syntax
